In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset)

In [5]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [6]:
dataset=dataset.astype(int)

In [7]:
dataset

      age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0    16884           1         0          0           1
1      18   33         1     1725           0         1          1           0
2      28   33         3     4449           0         1          1           0
3      33   22         0    21984           0         1          1           0
4      32   28         0     3866           0         1          1           0
...   ...  ...       ...      ...         ...       ...        ...         ...
1333   50   30         3    10600           0         1          1           0
1334   18   31         0     2205           1         0          1           0
1335   18   36         0     1629           1         0          1           0
1336   21   25         0     2007           1         0          1           0
1337   61   29         0    29141           1         0          0           1

[1338 rows x 8 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_female', 'sex_male','smoker_no', 'smoker_yes']]

In [10]:

independent

      age  bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0           1         0          0           1
1      18   33         1           0         1          1           0
2      28   33         3           0         1          1           0
3      33   22         0           0         1          1           0
4      32   28         0           0         1          1           0
...   ...  ...       ...         ...       ...        ...         ...
1333   50   30         3           0         1          1           0
1334   18   31         0           1         0          1           0
1335   18   36         0           1         0          1           0
1336   21   25         0           1         0          1           0
1337   61   29         0           1         0          0           1

[1338 rows x 7 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],
            'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}


grid=GridSearchCV(SVR(),  param_grid,  refit=True, verbose=3,n_jobs=-1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
re=grid.cv_results_

print("The R_score value for best parameter{}:".format(grid.best_params_))

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.109803,0.009307,0.068446,0.028490,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.016925,0.023857,-0.090482,-0.080577,-0.089825,-0.044020,0.052754,35
1,0.142629,0.042118,0.030516,0.018655,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.149667,0.150484,0.054840,0.082914,0.045622,0.096705,0.045276,32
2,0.100729,0.007612,0.020239,0.007304,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.082200,0.096221,-0.015336,-0.008093,-0.019583,0.027082,0.051054,34
3,0.075776,0.004186,0.014936,0.008264,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.517823,0.590514,0.473699,0.495851,0.461277,0.507833,0.045633,23
4,0.091132,0.005481,0.051761,0.004665,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.017126,0.023808,-0.090460,-0.080687,-0.089904,-0.044023,0.052813,36
5,0.076727,0.006820,0.020400,0.007459,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.145064,0.151566,0.054353,0.085792,0.047169,0.096789,0.044079,31
6,0.102994,0.005197,0.017050,0.001591,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.081595,0.096382,-0.015406,-0.007721,-0.019365,0.027097,0.050888,33
7,0.081393,0.005031,0.010250,0.007380,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.517823,0.590514,0.473699,0.495851,0.461277,0.507833,0.045633,23
8,0.093055,0.004480,0.047910,0.005658,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.381888,0.409228,0.261388,0.312168,0.267634,0.326461,0.059702,27
9,0.082061,0.007466,0.014967,0.000987,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.688264,0.687532,0.646360,0.684757,0.586474,0.658677,0.039378,14
10,0.101798,0.005734,0.026141,0.005685,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.496553,0.571528,0.457169,0.476341,0.456137,0.491546,0.042636,26
11,0.100308,0.005715,0.017539,0.002014,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.595740,0.688316,0.562351,0.621784,0.560799,0.605798,0.047071,21
12,0.094042,0.009228,0.060515,0.006376,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.382701,0.408924,0.261530,0.311382,0.267311,0.326369,0.059842,28
13,0.085154,0.009756,0.011003,0.009463,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.682968,0.688789,0.645938,0.687524,0.588370,0.658718,0.038560,13
14,0.108433,0.003757,0.019768,0.004393,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.497252,0.571183,0.457436,0.477427,0.456342,0.491928,0.042370,25
15,0.096312,0.004932,0.016628,0.001515,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.595740,0.688316,0.562351,0.621784,0.560799,0.605798,0.047071,21
16,0.118165,0.005989,0.051070,0.006499,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.766929,0.757487,0.712170,0.748569,0.667124,0.730456,0.036700,12
17,0.123177,0.004331,0.016564,0.003795,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.849675,0.809499,0.815627,0.807139,0.756636,0.807715,0.029785,5
18,0.141001,0.010432,0.024577,0.005802,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.342192,0.334921,0.209294,0.235702,0.330859,0.290594,0.056341,29
19,0.153530,0.006044,0.013066,0.002248,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605846,0.583265,0.697402,0.532385,0.681590,0.620097,0.061661,19
20,0.141553,0.006710,0.077966,0.008226,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.767355,0.757444,0.712232,0.748279,0.667011,0.730464,0.036783,11
21,0.156061,0.008539,0.021256,0.003788,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.849319,0.809499,0.815617,0.807311,0.756584,0.807666,0.029702,6
22,0.160913,0.015139,0.026898,0.007099,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.348496,0.223004,0.192023,0.230309,0.328817,0.264530,0.062187,30
23,0.154178,0.010874,0.020606,0.005869,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605846,0.583265,0.697402,0.532385,0.681590,0.620097,0.061661,19
24,0.156471,0.006654,0.066787,0.009294,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.836745,0.786262,0.802335,0.805022,0.742870,0.794647,0.030627,10
25,0.203062,0.022505,0.020772,0.004990,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.854571,0.810672,0.817985,0.801889,0.762901,0.809603,0.029442,4
26,0.159529,0.013544,0.023993,0.004053,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.347708,-0.767083,-2.046939,-2.938092,-0.277080,-1.675380,0.996471,38
27,0.292075,0.209156,0.018985,0.004803,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.660697,0.583238,0.697889,0.529468,0.655758,0.625410,0.060667,15
28,0.163280,0.005436,0.063337,0.003882,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.837109,0.786230,0.802370,0.804811,0.742795,0.794663,0.030742,9
29,0.197301,0.022117,0.016088,0.003846,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.854620,0.810683,0.817982,0.801847,0.762977,0.809622,0.029435,3
30,0.167049,0.007926,0.022384,0.006122,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.204867,-0.891129,-2.032593,-0.931279,-0.343907,-1.280755,0.717059,37
31,0.288898,0.209825,0.018220,0.004517,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.660697,0.583238,0.697889,0.529468,0.655758,0.625410,0.060667,15
32,0.180224,0.008614,0.062547,0.004087,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.847342,0.797438,0.818400,0.811205,0.750868,0.805051,0.031618,8
33,0.686287,0.791460,0.024100,0.010246,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.854559,0.808299,0.818005,0.802203,0.765544,0.809722,0.028598,2
34,0.157638,0.007925,0.022867,0.006315,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-5.435676,-5.864729,-5.626211,-4.584056,-3.567264,-5.015587,0.843118,39
35,0.221945,0.012152,0.022873,0.007754,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.660689,0.581394,0.697888,0.529293,0.655755,0.625004,0.060981,17
36,0.178618,0.023542,0.064443,0.012615,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.847604,0.797383,0.818416,0.811214,0.750791,0.805082,0.031718,7
37,0.815859,1.107869,0.014358,0.007216,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.854673,0.808251,0.818004,0.802203,0.765530,0.809732,0.028638,1
38,0.157574,0.016486,0.023168,0.007262,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-5.262475,-5.777963,-5.654874,-5.015024,-3.595298,-5.061127,0.782011,40
39,0.207556,0.015383,0.016441,0.001803,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.660689,0.581394,0.697888,0.529293,0.655755,0.625004,0.060981,17

In [19]:
age_input=float(input("age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_female_input=int(input("sex female 0 or 1:"))
sex_male_input=int(input("sex male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))
smoker_no_input=int(input("smoker no 0 or 1:"))

age: 32
BMI: 14.5
children: 2
sex female 0 or 1: 0
sex male 0 or 1: 1
smoker yes 0 or 1: 0
smoker no 0 or 1: 1

In [21]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_female_input,sex_male_input,smoker_yes_input,smoker_no_input]])


print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[4511134.01823039]